### DISCUSSION TITLE
Can NBomber Cluster run with later than 2.9.9 versions of NATS?

### DISCUSSION THREAD

**Discussion by mrm-gith-b** [VIP-Logic/NBomber#797] [General]
I was looking at running this AMI https://aws.amazon.com/marketplace/pp/prodview-hpdcuy2nkknl4 for NATS but it seems the oldest version offered is 2.9.11. Would this or later versions still work?

**Comment by AntyaDev** [comment]
I haven't tried it, but if it's higher than 2.9, which it seems to be, it should work.
The important point is to run JetStream.

```yml
version: "3.4"
services:

    nats:
        image: "nats:2.9.9"
        command: --js
        ports:
            - "8222:8222"
            - "4222:4222"
```

`command: --js`

it enables JetStream
https://nbomber.com/docs/getting-started/installation#install-nats-message-broker
